In [1]:
a = [[2.1,3.1,4.1] ,[ 5.1,6.1,7.1] , [8.1,9.1,10.1] , [11.1,12.1,13.1] , [14.1,15.1,16.1]]
b = [[2.1,3.1,4.1,5.1] , [2.1,3.1,4.1,5.1] , [2.1,3.1,4.1,5.1]]

In [2]:
import numpy as np

a_np = np.array(a)
b_np = np.array(b)

c = np.matmul(a_np, b_np)
print(c)

[[ 19.53  28.83  38.13  47.43]
 [ 38.43  56.73  75.03  93.33]
 [ 57.33  84.63 111.93 139.23]
 [ 76.23 112.53 148.83 185.13]
 [ 95.13 140.43 185.73 231.03]]
